"""SQLite persistence for chat sessions — the durable half of the chat store.

The in-memory ``BoundedStore`` in ``chat.py`` holds live agents; this store
holds the conversation history so a browser can resume a session across page
reloads *and* server restarts.  Same architecture as the knowledge
``vector_store``: stdlib ``sqlite3``, one connection per thread
(``check_same_thread=False``), a gitignored DB file at ``data/chat.db``.

Deployment caveat: Vercel's filesystem is ephemeral, so on that deploy this is
session-local only; production would back it with Postgres/Redis.  The
frontend owns the list of session ids (localStorage) and passes them here, so
there is deliberately no global "list all sessions" endpoint.

Privacy: the user has opted in to saving their own chat history, and the input
guard already redacts personal data before any text reaches the model, so the
persisted rows hold already-scrubbed conversation text.  ``config/privacy.yaml``
is left untouched.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_SCHEMA = """
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    brief_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT,
    tool_trace_json TEXT,
    tool_calls_json TEXT,
    tool_call_id TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_msg_session ON messages(session_id, id);
"""

# Session ids are opaque hex strings generated by the caller (uuid4().hex), so
# a sessions row always exists before its first messages.
DEFAULT_TITLE = "New conversation"
_TITLE_LIMIT = 48


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def auto_title(message: str) -> str:
    """A short, readable title from the first user message."""
    title = " ".join(message.split())[:_TITLE_LIMIT].strip()
    return title or DEFAULT_TITLE


class ChatStore:
    """SQLite-backed session + message store.

    Thread-safe: sqlite3 connections are not safe to share across threads even
    with ``check_same_thread=False``, so every public method serialises on one
    re-entrant lock (the chat routes already serialise per session, but turns
    on *different* sessions can interleave writes).
    """

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(str(self.path), check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self.conn.executescript(_SCHEMA)
        # Migrate DBs created before tool_calls/tool_call_id were persisted:
        # the LLM tool loop needs them back verbatim on resume, so add the
        # columns when missing (a fresh schema already declares them).
        msg_cols = {row[1] for row in self.conn.execute("PRAGMA table_info(messages)")}
        if "tool_calls_json" not in msg_cols:
            self.conn.execute("ALTER TABLE messages ADD COLUMN tool_calls_json TEXT")
        if "tool_call_id" not in msg_cols:
            self.conn.execute("ALTER TABLE messages ADD COLUMN tool_call_id TEXT")
        self.conn.commit()
        self._lock = threading.RLock()

    def close(self) -> None:
        with self._lock:
            self.conn.close()

    # ------------------------------------------------------------------
    # Sessions
    # ------------------------------------------------------------------

    def create_session(self, session_id: str, title: str = DEFAULT_TITLE) -> None:
        """Insert a session row (idempotent — write-through from create)."""
        now = _now_iso()
        with self._lock:
            self.conn.execute(
                "INSERT OR IGNORE INTO sessions (id, title, brief_json, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?)",
                (session_id, title, "{}", now, now),
            )
            self.conn.commit()

    def rename_session(self, session_id: str, title: str) -> bool:
        """Rename a session; False when the session does not exist."""
        now = _now_iso()
        with self._lock:
            cur = self.conn.execute(
                "UPDATE sessions SET title = ?, updated_at = ? WHERE id = ?",
                (title, now, session_id),
            )
            self.conn.commit()
        return cur.rowcount > 0

    def delete_session(self, session_id: str) -> None:
        """Drop the session and its messages (FK cascade is off, so both go)."""
        with self._lock:
            self.conn.execute("DELETE FROM messages WHERE session_id = ?", (session_id,))
            self.conn.execute("DELETE FROM sessions WHERE id = ?", (session_id,))
            self.conn.commit()

    # ------------------------------------------------------------------
    # Messages / turns
    # ------------------------------------------------------------------

    def save_turn(
        self,
        session_id: str,
        messages: list[dict[str, Any]],
        brief: dict[str, Any] | None = None,
        *,
        turn_trace: list[dict[str, Any]] | None = None,
        title: str | None = None,
    ) -> None:
        """Append one turn's messages (system rows skipped — the agent
        re-seeds its system prompt idempotently on resume).

        Idempotent against resume: a session restored from SQLite carries the
        already-persisted messages back in memory, so only the NEW tail past
        the currently-stored row count is inserted (the store only ever grows,
        and every persist writes the full non-system memory, so the stored
        count is exactly the length of the memory prefix already on disk).

        ``turn_trace`` is attached to the LAST inserted row (the turn's final
        assistant answer) so the UI can re-render charts on resume.
        """
        now = _now_iso()
        with self._lock:
            # Auto-title once, from the first real user message (only fires
            # while the session still carries the default title).
            auto = ""
            if not title:
                first_user = next(
                    (m.get("content") for m in messages if m.get("role") == "user"), None
                )
                auto = auto_title(first_user) if first_user else ""
            self.conn.execute(
                "INSERT OR IGNORE INTO sessions (id, title, brief_json, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?)",
                (session_id, auto or DEFAULT_TITLE, "{}", now, now),
            )
            if auto:
                self.conn.execute(
                    "UPDATE sessions SET title = ? WHERE id = ? AND title = ?",
                    (auto, session_id, DEFAULT_TITLE),
                )
            if brief:
                self.conn.execute(
                    "UPDATE sessions SET brief_json = ?, updated_at = ? WHERE id = ?",
                    (json.dumps(brief, ensure_ascii=False), now, session_id),
                )
            # Only the tail beyond the rows already on disk is new (see the
            # docstring).  The count matches because every persist writes all
            # non-system messages and nothing deletes message rows except the
            # whole-session purge.
            stored = self.conn.execute(
                "SELECT COUNT(*) FROM messages WHERE session_id = ?", (session_id,)
            ).fetchone()[0]
            last_id: int | None = None
            for m in [m for m in messages if m.get("role") != "system"][stored:]:
                cur = self.conn.execute(
                    "INSERT INTO messages (session_id, role, content, tool_trace_json, "
                    "tool_calls_json, tool_call_id, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        session_id,
                        m.get("role"),
                        m.get("content"),
                        None,
                        json.dumps(m["tool_calls"], ensure_ascii=False) if m.get("tool_calls") else None,
                        m.get("tool_call_id"),
                        now,
                    ),
                )
                last_id = cur.lastrowid
            if turn_trace and last_id is not None:
                self.conn.execute(
                    "UPDATE messages SET tool_trace_json = ? WHERE id = ?",
                    (json.dumps(turn_trace, ensure_ascii=False), last_id),
                )
            self.conn.execute(
                "UPDATE sessions SET updated_at = ? WHERE id = ?", (now, session_id)
            )
            self.conn.commit()

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def get_session(self, session_id: str) -> dict[str, Any] | None:
        """The full persisted session, or None when unknown.

        ``history`` is every stored message row as ``{role, content,
        tool_trace}`` (``content`` may be None for mid-loop tool-call assistant
        rows; ``tool_trace`` is the parsed list or None).  Callers decide
        whether to filter for the UI.
        """
        with self._lock:
            row = self.conn.execute(
                "SELECT id, title, brief_json, created_at, updated_at FROM sessions WHERE id = ?",
                (session_id,),
            ).fetchone()
            if row is None:
                return None
            messages = self.conn.execute(
                "SELECT role, content, tool_trace_json, tool_calls_json, tool_call_id "
                "FROM messages WHERE session_id = ? ORDER BY id",
                (session_id,),
            ).fetchall()
        brief_json = row["brief_json"]
        return {
            "session_id": row["id"],
            "title": row["title"],
            "brief_json": brief_json,
            "created_at": row["created_at"],
            "updated_at": row["updated_at"],
            "history": [
                {
                    "role": m["role"],
                    "content": m["content"],
                    "tool_trace": (
                        json.loads(m["tool_trace_json"]) if m["tool_trace_json"] else None
                    ),
                    "tool_calls": (
                        json.loads(m["tool_calls_json"]) if m["tool_calls_json"] else None
                    ),
                    "tool_call_id": m["tool_call_id"],
                }
                for m in messages
            ],
        }

    def get_sessions(self, session_ids: list[str]) -> list[dict[str, Any]]:
        """The persisted sessions for the given ids, in input order.

        Unknown ids are skipped (the frontend prunes its own list from what
        comes back).  Used to repopulate the sidebar after a reload.
        """
        out: list[dict[str, Any]] = []
        for sid in session_ids:
            session = self.get_session(sid)
            if session is not None:
                out.append(session)
        return out
